openmvs_bin: "/usr/local/bin/OpenMVS/"

densify:
  max_resolution: 1200
  min_resolution: 480
  sub_resolution_levels: 2
  postprocess_dmaps: 1  # 2=fill gaps, 1=remove speckles (fast), 0=disabled
  fusion_mode: -2  # -2=fuse disparity-maps (fast), 0=depth-maps & fusion, -1=depth-maps only

mesh:
  poisson_depth: 8
  preclean: false
  threads: null
  target_faces: 500000
  max_hole_size: 2000000

texture:
  use_highres: false
  scale: 0.5

postprocess:
  close_holes: false
  smooth_iterations: 0
