openmvs_bin: "/usr/local/bin/OpenMVS/"

densify:
  max_resolution: 2400
  min_resolution: 800
  sub_resolution_levels: 3
  postprocess_dmaps: 2  # 2=fill gaps in depth maps, 1=remove speckles, 0=disabled
  fusion_mode: 0  # 0=depth-maps & fusion (default), -1=depth-maps only, -2=fuse disparity-maps

mesh:
  poisson_depth: 11
  preclean: true
  threads: null
  target_faces: 2000000
  max_hole_size: 500000

texture:
  use_highres: true
  scale: 1.0

postprocess:
  close_holes: true
  smooth_iterations: 3
