defaults:
  - dataset: friedrichs_house
  - stage1: default
  - stage2: superpoint_lightglue #disk_lightglue
  - geofencing: loose
  - mvs: default
  - reset: conservative
  - _self_

output_root: ${dataset.root}/output/hloc/${dataset.experiment}

logging:
  level: INFO
  log_file: pipeline.log
  directory: cwd 

mvs:
  enabled: true